BASE: ['../config.py']

MODEL:
  TYPE: 'mobilemamba'
  NAME: 'mobilemamba_tiny'
  MOBILEMAMBA:
    PATCH_SIZE: 4
    IN_CHANS: 3
    OUT_CHANS: 36
    DEPTHS: [2, 2, 6, 2]
    EMBED_DIM: [96, 192, 384, 768]
    TYPE: 's'
    ED: 96
    GLOBAL_RATIO: 0.5
    LOCAL_RATIO: 0.5
    KERNELS: [3, 3, 3, 3]

DATA:
  TRAIN_BATCH: 4
  TEST_BATCH: 1
  DATASET: 'DIV2K'
  IMG_SIZE: 256
  train_data_dir: "/mnt/wutong/datasets/DIV2K/DIV2K_train_HR"
  test_data_dir: "/mnt/wutong/datasets/DIV2K/DIV2K_valid_HR"
  INTERPOLATION: 'bicubic'
  ZIP_MODE: False
  CACHE_MODE: 'part'
  PIN_MEMORY: True
  NUM_WORKERS: 8
  REQUIRE_DISTRIBUTION: True
  RANGE: 5
  SCALE: 10000

CHANNEL:
  TYPE: 'awgn'
  SNR: [20]
  ADAPTIVE: 'CA'
  INPUT: 'conv'

TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 20
  BASE_LR: 1e-4
  WARMUP_LR: 5e-7
  MIN_LR: 5e-6
  WEIGHT_DECAY: 0.05
  CLIP_GRAD: 5.0
  AUTO_RESUME: True
  ACCUMULATION_STEPS: 1
  USE_CHECKPOINT: False
  LOSS: 'MSE'
  DATA_PARALLEL: False
  EVAL_MATRIX: 'PSNR'
  GAN_LOSS: False
  DIS_WEIGHT: 0.5
  START_EPOCH: 0
  ENCODER_PATH: '/mnt/wutong/MambaJSCCcheckpoints/Journal/encoder'
  DECODER_PATH: '/mnt/wutong/MambaJSCCcheckpoints/Journal/decoder'

OUTPUT: 'output/mobilemamba_tiny_DIV2K'
TAG: 'default' 