# only for eval
TRAIN:
  EPOCHS: 1000
  SAVE_FRE: 100
  LOSS: 'PSNR' 
  EVAL_MATRIX: 'PSNR'
  ENCODER_PATH: '/mnt/sda/wt/MambaJSCCcheckpoints/DIV2K/encoder'  
  DECODER_PATH: '/mnt/sda/wt/MambaJSCCcheckpoints/DIV2K/decoder'
  GAN_LOSS: False
DATA:
  DATASET: "CIFAR10"
  TRAIN_BATCH: 64
  TEST_BATCH: 20
  IMG_SIZE: 256 
  train_data_dir: "/mnt/sda/datasets/CIFAR10/"
  test_data_dir:  "/mnt/sda/datasets/CIFAR10/"
CHANNEL:
  TYPE: 'awgn'
  SNR : [10] # [1,3,5,7,9,11,13,15,17,20]
  ADAPTIVE: 'no'

