
TRAIN:
  EPOCHS: 1
  SAVE_FRE: 1
  LOSS: 'PSNR'
  EVAL_MATRIX: 'PSNR'
  ENCODER_PATH: '/mnt/sda/wt/MambaJSCCcheckpoints/AFHQ/encoder'  
  DECODER_PATH: '/mnt/sda/wt/MambaJSCCcheckpoints/AFHQ/decoder'
  GAN_LOSS: False
  DATA_PARALLEL: False
DATA:
  DATASET: "AFHQ"
  TRAIN_BATCH: 2
  TEST_BATCH: 1
  IMG_SIZE: 512
  train_data_dir: "/mnt/sda/datasets/AFHQ/afhq/train"
  test_data_dir:  "/mnt/sda/datasets/AFHQ/afhq/val"
CHANNEL:
  TYPE: 'awgn'
  SNR :  [1,3,5,7,9,11,13,15,17,20] # 
  ADAPTIVE: 'ssm'


