
TRAIN:
  EPOCHS: 40
  SAVE_FRE: 10
  LOSS: 'PSNR'
  EVAL_MATRIX: 'PSNR' 
  ENCODER_PATH: '/mnt/sda/wt/MambaJSCCcheckpoints/CelebA/encoder'  
  DECODER_PATH: '/mnt/sda/wt/MambaJSCCcheckpoints/CelebA/decoder'
  GAN_LOSS: False
DATA:
  DATASET: "CelebA"
  TRAIN_BATCH: 20
  TEST_BATCH: 1
  IMG_SIZE: 128     
  train_data_dir: r"/mnt/sda/datasets/CelebA/Img/trainset" 
  test_data_dir:  r"/mnt/sda/datasets/CelebA/Img/validset"
CHANNEL:
  TYPE: 'awgn'
  SNR:  [1,3,5,7,9,11,13,15,17,20] # [1,3,5,7,9,11,13,15,17,20]
  ADAPTIVE: 'ssm'
